apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: po2wg6q6o-dotnet-basic
  janus-idp.io/tekton: po2wg6q6o-dotnet-basic
  backstage.io/kubernetes-id: po2wg6q6o-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: po2wg6q6o-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
